-- Numeração da Tarefa (OS) começando em 04700.
alter table public.tarefas alter column numero set generated by default;
update public.tarefas set numero = 4700 where numero = 6;
alter table public.tarefas alter column numero restart with 4701;

-- Campos novos na Tarefa: Pedido de Compra (PC) e Tipo de tarefa (reusa tipos_servico).
alter table public.tarefas
  add column if not exists pedido_compra text,
  add column if not exists tipo_servico_id uuid references public.tipos_servico(id);

-- Anexos da Tarefa (arquivos no bucket rat-anexos, pasta tarefas/<id>/).
create table if not exists public.tarefa_anexos (
  id uuid primary key default gen_random_uuid(),
  tarefa_id uuid not null references public.tarefas(id) on delete cascade,
  nome text not null,
  url text not null,
  mime text,
  tamanho bigint,
  criado_por uuid,
  criado_em timestamptz not null default now()
);
create index if not exists ix_ta_tarefa on public.tarefa_anexos (tarefa_id);
alter table public.tarefa_anexos enable row level security;
drop policy if exists ta_office_all on public.tarefa_anexos;
create policy ta_office_all on public.tarefa_anexos for all
  using (public.app_role() in ('admin','gestor_axis'))
  with check (public.app_role() in ('admin','gestor_axis'));

-- Equipamentos relacionados à Tarefa (N:N com equipamentos_axis).
create table if not exists public.tarefa_equipamentos (
  tarefa_id uuid not null references public.tarefas(id) on delete cascade,
  equipamento_id uuid not null references public.equipamentos_axis(id) on delete cascade,
  criado_em timestamptz not null default now(),
  primary key (tarefa_id, equipamento_id)
);
alter table public.tarefa_equipamentos enable row level security;
drop policy if exists te_office_all on public.tarefa_equipamentos;
create policy te_office_all on public.tarefa_equipamentos for all
  using (public.app_role() in ('admin','gestor_axis'))
  with check (public.app_role() in ('admin','gestor_axis'));

-- Nota: a pasta tarefas/ no bucket rat-anexos já é coberta pela policy rat_anexos_admin
-- (admin/gestor têm acesso total ao bucket), então não é preciso policy de storage nova.
